const assert=require('assert');
const U=require('../web/us_market.js');
assert.strictEqual(U.safeURL('javascript:alert(1)'),'');
assert.strictEqual(U.safeURL('https://user:secret@example.com'),'');
assert.strictEqual(U.safeURL('https://example.com/a'),'https://example.com/a');
assert.strictEqual(U.esc('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;');
assert(U.time('2026-10-02').includes('仅日期'));
assert(U.time('2026-10-02T10:00:00').includes('待核验'));
assert(U.time('2026-10-02T10:00:00Z').includes('18:00:00'));
assert(U.time('2026-10-02T09:57:54.000-0400').includes('21:57:54'));
const bad=U.quotes({SPY:{price:9999,pct:99,data_status:'stale',as_of:'2026-09-01',source:'<bad>'}},['SPY']);
assert(!bad.includes('9,999'));assert(!bad.includes('99.00%'));assert(bad.includes('过期'));assert(bad.includes('&lt;bad&gt;'));
assert(U.quotes({'^TNX':{price:4.1,prev:4,pct:2.5,data_status:'ok'}},['^TNX']).includes('+10.0 bp'));
const article=U.articles([{title:'<img onerror=alert(1)>',link:'javascript:alert(1)',zh:'<unsafe>',source:'a',points:[]}],'');
assert(!article.includes('href="javascript'));assert(!article.includes('<img'));assert(article.includes('未取得核验正文'));
const run={run_id:'test',mode:'digest',started_at:'2026-10-02T10:00:00Z',data_status:'unavailable',quotes:{},news:[],sources:[]};
assert(U.report(run,{alerts:[]}).includes('无法判断是否存在重要事件'));
assert(U.report(run,{alerts:[]}).includes('不代表实时行情'));
assert(!U.report(run,{alerts:[]}).includes('今日无事件'));
const older={...run,run_id:'old',data_status:'partial'};
const newer={...run,run_id:'new',started_at:'2026-10-02T11:00:00Z'};
assert.strictEqual(U.preferred({digest:[older,newer],alerts:[]}).run_id,'new');
assert(U.report(null,{}).includes('尚无已完成'));
assert.deepStrictEqual(U.parseSymbols(' nvda，AAPL aapl\nBRK.B; BF-B、123 '),['NVDA','AAPL','BRK.B','BF-B','123']);
assert.deepStrictEqual(U.parseSymbols(' , \n'),[]);
for(const input of ['<img>','AAPL/US','ABCDEFGHIJK','^','..'])assert.throws(()=>U.parseSymbols(input),/代码格式无效/);
assert.throws(()=>U.parseSymbols('SPY'),/固定市场/);
assert.throws(()=>U.parseSymbols(Array.from({length:101},(_,i)=>'S'+i).join(',')),/最多 100/);
const revision='a'.repeat(64);
const requestURL=new URL(U.configURL(['nvda','BRK.B'],revision));
assert.strictEqual(requestURL.origin,'https://github.com');
assert.strictEqual(requestURL.pathname,'/conan841120-cmyk/us-trader-daily/issues/new');
assert.strictEqual(requestURL.searchParams.get('title'),'[美股配置] 更新自选代码');
assert.deepStrictEqual(JSON.parse(requestURL.searchParams.get('body').split('\n')[1]),{base_revision:revision,symbols:['NVDA','BRK.B']});
assert.throws(()=>U.configURL(['NVDA'],'bad'),/云端配置版本/);
const configured={...run,quotes:{NVDA:{price:120,data_status:'ok'},AAPL:{price:220,data_status:'ok'}}};
assert.deepStrictEqual(U.defaultSymbols({...run,quotes:{SPY:{},TLT:{},NVDA:{},AAPL:{}}}),['NVDA','AAPL']);
const personalized=U.report(configured,{alerts:[{...run,heads:['测试预警']}]},['BRK.B','NVDA']);
assert(personalized.includes('<details id="other-quotes" open>'));
assert(personalized.includes('<details open><summary>'));
assert(personalized.includes('<details id="source-status">'));
assert(!personalized.includes('<details id="source-status" open'));
assert(personalized.includes('BRK.B</td><td colspan="3">行情缺失'));
assert(!personalized.includes('AAPL<div'));
assert(personalized.indexOf('BRK.B</td>')<personalized.indexOf('NVDA<div'));
assert(U.report(configured,{alerts:[]},[]).includes('自选清单为空'));
// 验证提交仅打开 GitHub 确认页，不把未确认的草稿当成云端配置。
const vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require.resolve('../web/us_market.js'),'utf8');
function browser(cloud){
  const nodes=Object.fromEntries(['date','run','load-status','download','report','watchlist-status','watchlist-input','cloud-request'].map(id=>[id,{value:'',innerHTML:'',textContent:'',events:{},addEventListener(type,handler){this.events[type]=handler;}}]));
  const opened=[];
  vm.runInNewContext(source,{window:{US_MARKET_BOOTSTRAP:{manifest:{dates:['2026-10-02'],watchlist:cloud},day:{date:'2026-10-02',digest:[configured,{...configured,run_id:'later',started_at:'2026-10-02T11:00:00Z'}],alerts:[]}},open:url=>opened.push(url)},document:{getElementById:id=>nodes[id]},URL,Intl,location:{href:'https://example.com/us-market/'},history:{replaceState(){}}});
  return {nodes,opened,save(value){nodes['watchlist-input'].value=value;nodes.report.events.submit({target:{id:'watchlist-form'},preventDefault(){}});}};
}
const session=browser({symbols:['NVDA','BRK.B'],revision});
assert(session.nodes.report.innerHTML.includes('NVDA, BRK.B</textarea>'));
session.save('cost, msft');
assert.deepStrictEqual(JSON.parse(new URL(session.opened[0]).searchParams.get('body').split('\n')[1]).symbols,['COST','MSFT']);
assert(session.nodes['watchlist-status'].textContent.includes('尚未保存'));
assert.strictEqual(session.nodes['cloud-request'].href,session.opened[0]);
session.nodes.run.value='test';session.nodes.run.events.change();
assert(session.nodes.report.innerHTML.includes('NVDA, BRK.B</textarea>'));
session.save('<script>');assert.strictEqual(session.opened.length,1);
assert(session.nodes['watchlist-status'].textContent.includes('代码格式无效'));
session.save('');assert.deepStrictEqual(JSON.parse(new URL(session.opened[1]).searchParams.get('body').split('\n')[1]).symbols,[]);
const waiting=browser();waiting.save('COST');assert.strictEqual(waiting.opened.length,0);
assert(waiting.nodes['watchlist-status'].textContent.includes('云端配置版本'));
console.log('美股前端验证通过：链接与文字安全、时间、缺失、历史快照、报价口径、自选清单和折叠默认值。');
