const assert=require('assert');
const U=require('../web/us_market.js');
assert.strictEqual(U.safeURL('javascript:alert(1)'),'');
assert.strictEqual(U.safeURL('https://user:secret@example.com'),'');
assert.strictEqual(U.safeURL('https://example.com/a'),'https://example.com/a');
assert.strictEqual(U.esc('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;');
assert(U.time('2026-10-02').includes('仅日期'));
assert(U.time('2026-10-02T10:00:00').includes('待核验'));
assert(U.time('2026-10-02T10:00:00Z').includes('18:00:00'));
assert(U.time('2026-10-02T09:57:54.000-0400').includes('21:57:54'));
const bad=U.quotes({SPY:{price:9999,pct:99,data_status:'stale',as_of:'2026-09-01',source:'<bad>'}},['SPY']);
assert(!bad.includes('9,999'));assert(!bad.includes('99.00%'));assert(bad.includes('过期'));assert(bad.includes('&lt;bad&gt;'));
assert(U.quotes({'^TNX':{price:4.1,prev:4,pct:2.5,data_status:'ok'}},['^TNX']).includes('+10.0 bp'));
const article=U.articles([{title:'<img onerror=alert(1)>',link:'javascript:alert(1)',zh:'<unsafe>',source:'a',points:[]}],'');
assert(!article.includes('href="javascript'));assert(!article.includes('<img'));assert(article.includes('未取得核验正文'));
const run={run_id:'test',mode:'digest',started_at:'2026-10-02T10:00:00Z',data_status:'unavailable',quotes:{},news:[],sources:[]};
assert(U.report(run,{alerts:[]}).includes('无法判断是否存在重要事件'));
assert(U.report(run,{alerts:[]}).includes('不代表实时行情'));
assert(!U.report(run,{alerts:[]}).includes('今日无事件'));
const older={...run,run_id:'old',data_status:'partial'};
const newer={...run,run_id:'new',started_at:'2026-10-02T11:00:00Z'};
assert.strictEqual(U.preferred({digest:[older,newer],alerts:[]}).run_id,'new');
assert(U.report(null,{}).includes('尚无已完成'));
console.log('美股前端验证通过：链接与文字安全、时间、缺失、历史快照与报价口径。');
