const assert=require('assert');
const U=require('../web/us_market.js');
assert.strictEqual(U.safeURL('javascript:alert(1)'),'');
assert.strictEqual(U.safeURL('https://user:secret@example.com'),'');
assert.strictEqual(U.safeURL('https://example.com/a'),'https://example.com/a');
assert.strictEqual(U.esc('<img src=x onerror=alert(1)>'),'&lt;img src=x onerror=alert(1)&gt;');
assert(U.time('2026-10-02').includes('仅日期'));
assert(U.time('2026-10-02T10:00:00').includes('待核验'));
assert(U.time('2026-10-02T10:00:00Z').includes('18:00:00'));
assert(U.time('2026-10-02T09:57:54.000-0400').includes('21:57:54'));
const bad=U.quotes({SPY:{price:9999,pct:99,data_status:'stale',as_of:'2026-09-01',source:'<bad>'}},['SPY']);
assert(!bad.includes('9,999'));assert(!bad.includes('99.00%'));assert(bad.includes('过期'));assert(bad.includes('&lt;bad&gt;'));
assert(U.quotes({'^TNX':{price:4.1,prev:4,pct:2.5,data_status:'ok'}},['^TNX']).includes('+10.0 bp'));
const article=U.articles([{title:'<img onerror=alert(1)>',link:'javascript:alert(1)',zh:'<unsafe>',source:'a',points:[]}],'');
assert(!article.includes('href="javascript'));assert(!article.includes('<img'));assert(article.includes('未取得核验正文'));
const run={run_id:'test',mode:'digest',started_at:'2026-10-02T10:00:00Z',data_status:'unavailable',quotes:{},news:[],sources:[]};
assert(U.report(run,{alerts:[]}).includes('无法判断是否存在重要事件'));
assert(U.report(run,{alerts:[]}).includes('不代表实时行情'));
assert(!U.report(run,{alerts:[]}).includes('今日无事件'));
const older={...run,run_id:'old',data_status:'partial'};
const newer={...run,run_id:'new',started_at:'2026-10-02T11:00:00Z'};
assert.strictEqual(U.preferred({digest:[older,newer],alerts:[]}).run_id,'new');
assert(U.report(null,{}).includes('尚无已完成'));
assert.deepStrictEqual(U.parseSymbols(' nvda，AAPL aapl\nBRK.B; BF-B、^GSPC；123 '),['NVDA','AAPL','BRK.B','BF-B','^GSPC','123']);
assert.deepStrictEqual(U.parseSymbols(' , \n'),[]);
for(const input of ['<img>','AAPL/US','ABCDEFGHIJK','^','..'])assert.throws(()=>U.parseSymbols(input),/代码格式无效/);
assert.strictEqual(U.readWatchlist({getItem:()=>null}),null);
assert.deepStrictEqual(U.readWatchlist({getItem:()=> '[]'}),[]);
assert.deepStrictEqual(U.readWatchlist({getItem:()=> '["nvda","NVDA","BRK.B"]'}),['NVDA','BRK.B']);
for(const value of ['{','{}','[null]','["<script>"]'])assert.throws(()=>U.readWatchlist({getItem:()=>value}));
assert.throws(()=>U.readWatchlist({getItem:()=>{throw new Error('disabled');}}),/disabled/);
const configured={...run,quotes:{NVDA:{price:120,data_status:'ok'},AAPL:{price:220,data_status:'ok'}}};
assert.deepStrictEqual(U.defaultSymbols({...run,quotes:{SPY:{},TLT:{},NVDA:{},AAPL:{}}}),['NVDA','AAPL']);
const personalized=U.report(configured,{alerts:[{...run,heads:['测试预警']}]},['BRK.B','NVDA']);
assert(personalized.includes('<details id="other-quotes" open>'));
assert(personalized.includes('<details open><summary>'));
assert(personalized.includes('<details id="source-status">'));
assert(!personalized.includes('<details id="source-status" open'));
assert(personalized.includes('BRK.B</td><td colspan="3">行情缺失'));
assert(!personalized.includes('AAPL<div'));
assert(personalized.indexOf('BRK.B</td>')<personalized.indexOf('NVDA<div'));
assert(U.report(configured,{alerts:[]},[]).includes('自选清单为空'));
// 在页面启动和表单事件之间验证保存、刷新及批次切换；不请求线上行情。
const vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require.resolve('../web/us_market.js'),'utf8');
function browser(storage){
  const nodes=Object.fromEntries(['date','run','load-status','download','report','watchlist-status','watchlist-input'].map(id=>[id,{value:'',innerHTML:'',textContent:'',events:{},addEventListener(type,handler){this.events[type]=handler;},focus(){}}]));
  vm.runInNewContext(source,{window:{US_MARKET_BOOTSTRAP:{manifest:{dates:['2026-10-02']},day:{date:'2026-10-02',digest:[configured,{...configured,run_id:'later',started_at:'2026-10-02T11:00:00Z'}],alerts:[]}},localStorage:storage},document:{getElementById:id=>nodes[id]},URL,Intl,location:{href:'https://example.com/us-market/'},history:{replaceState(){}}});
  return {nodes,save(value){nodes['watchlist-input'].value=value;nodes.report.events.submit({target:{id:'watchlist-form'},preventDefault(){}});}};
}
let saved=null;
const storage={getItem:()=>saved,setItem:(key,value)=>{saved=value;}};
const session=browser(storage);
session.save(' nvda, NVDA, BRK.B ');
assert.strictEqual(saved,'["NVDA","BRK.B"]');
assert(session.nodes['watchlist-status'].textContent.includes('已保存 2 个代码'));
const reloaded=browser(storage);
assert(reloaded.nodes.report.innerHTML.includes('NVDA, BRK.B</textarea>'));
reloaded.nodes.run.value='test';reloaded.nodes.run.events.change();
assert(reloaded.nodes.report.innerHTML.includes('NVDA, BRK.B</textarea>'));
reloaded.save('<script>');assert.strictEqual(saved,'["NVDA","BRK.B"]');
assert(reloaded.nodes['watchlist-status'].textContent.includes('代码格式无效'));
reloaded.save('');assert.strictEqual(saved,'[]');
assert(browser(storage).nodes.report.innerHTML.includes('自选清单为空'));
const blocked=browser({getItem:()=>null,setItem:()=>{throw new Error('blocked');}});
blocked.save('nvda');assert(blocked.nodes['watchlist-status'].textContent.includes('浏览器不允许保存'));
assert(blocked.nodes.report.innerHTML.includes('NVDA</textarea>'));
assert(browser({getItem:()=>'{'}).nodes['watchlist-status'].textContent.includes('未能读取'));
console.log('美股前端验证通过：链接与文字安全、时间、缺失、历史快照、报价口径、自选清单和折叠默认值。');
