import React, {useMemo, useState} from 'react';
import {DataComponent, DataTable, Dropdown, SegmentedControl, Slider, Switch, SortableRegion, SortableItem, useDataApp} from './ui.jsx';
import {STARTS,WINDOWS,LEVELS,ERA_COLORS,pct,signed,num,ci,bin,inBin,rank,summary,rollingBand,Gauge,LinePlot,ThresholdBars} from './visuals.jsx';

const eraChoices=STARTS.map(y=>({value:String(y),label:y===2010?'2010年之后':y+'年以来'}));
const maChoices=[{value:'200',label:'200日偏离度'},{value:'60',label:'60日偏离度'}];
const yearScope=y=>[{field:'start_year',label:'历史起点',value:y}];
const priceColors={close:'#14100c',sma60:'#2e4a6b',sma200:'#9a7736'},priceLabels={close:'收盘价',sma60:'60日均线',sma200:'200日均线'};
const biasColors={bias60:'#2e4a6b',bias200:'#9a7736'},biasLabels={bias60:'60日偏离',bias200:'200日偏离'};
const pp=v=>Number.isFinite(v)?(v>=0?'+':'')+v.toFixed(1)+'百分点':'—';
function HeatCell({row,metric='p_up'}){
 const value=row?.[metric];return <td style={{background:Number.isFinite(value)?'color-mix(in srgb, '+(metric==='p_up'?'#5c6b45':'#8a1f12')+' '+Math.round(6+value*39)+'%, var(--surface))':undefined}} title={row?.n?'年簇95%区间：'+(row.bootstrap_degenerate?'退化，勿解读':row[metric+'_ci95'].map(pct).join('–')):'无成熟样本'}><strong>{pct(value)}</strong><span>n = {row?.n??0} 日</span><small>均收益 {signed(row?.mean_return==null?null:100*row.mean_return)}{row&&(row.n<30||row.event_years<5)?' · 小样本':''}</small></td>;
}
function EraStats({stats,value,year,active}){
 return <div className={'sp-era-stat'+(active?' sp-selected':'')} data-reviewed-rows><div className="sp-mini-title"><b>{year}年以来</b><span>{num(stats.n)} 日</span></div><dl className="sp-pairs"><div><dt>中位数 / 均值</dt><dd>{signed(stats.median)} / {signed(stats.mean)}</dd></div><div><dt>标准差</dt><dd>{stats.sd.toFixed(2)}%</dd></div><div><dt>5% / 95% 分位</dt><dd>{signed(stats.q5)} / {signed(stats.q95)}</dd></div><div><dt>极小 / 极大</dt><dd>{signed(stats.min)} / {signed(stats.max)}</dd></div><div><dt>当前所处分位</dt><dd className="sp-purple">第 {rank(stats.values,value).toFixed(1)}%</dd></div></dl></div>;
}
export function DashboardContent(){
 const {snapshot,reviewedRows}=useDataApp();
 const daily=reviewedRows('daily',['date']),latest=daily.at(-1),previous=daily.at(-2),states=reviewedRows('state_stats'),events=reviewedRows('event_stats'),register=reviewedRows('events'),baselines=reviewedRows('baselines');
 const [year,setYear]=useState('2010'),[range,setRange]=useState('5y'),[curves,setCurves]=useState('both'),[showBand,setShowBand]=useState(true),[focusYear,setFocusYear]=useState(null);
 const [miniMA,setMiniMA]=useState('200'),[distMA,setDistMA]=useState('200'),[eventMA,setEventMA]=useState('200'),[side,setSide]=useState('bottom'),[horizon,setHorizon]=useState('20');
 const [heatMA,setHeatMA]=useState('200'),[heatMetric,setHeatMetric]=useState('p_up'),[bottomMA,setBottomMA]=useState('200'),[topMA,setTopMA]=useState('200'),[detailThreshold,setDetailThreshold]=useState('-15'),[simPrice,setSimPrice]=useState(latest.close);
 const periods=useMemo(()=>Object.fromEntries(STARTS.map(y=>[y,daily.filter(r=>r.date>=y+'-01-01')])),[daily]);
 const stats=useMemo(()=>Object.fromEntries([60,200].map(m=>[m,Object.fromEntries(STARTS.map(y=>[y,summary(periods[y],m)]))])),[periods]);
 const bandRows=useMemo(()=>rollingBand(daily),[daily]);
 const historyRows=useMemo(()=>{let start=range==='5y'?String(Number(latest.date.slice(0,4))-5)+latest.date.slice(4):range+'-01-01',end=latest.date;if(focusYear){start=(focusYear-1)+'-01-01';end=(focusYear+1)+'-12-31';}return bandRows.filter(r=>r.date>=start&&r.date<=end);},[bandRows,range,focusYear,latest.date]);
 const selectedDaily=periods[year],periodStats=stats[200][year],base=(y,w,metric='p_up')=>baselines.find(r=>r.start_year===Number(y)&&r.horizon===w)?.[metric];
 const matching=(m,v,y=year)=>states.filter(r=>r.ma===Number(m)&&r.start_year===Number(y)&&inBin(v,r));
 const current200=matching(200,latest.bias200),current60=matching(60,latest.bias60);
 const fields=curves==='both'?['bias60','bias200']:['bias'+curves],priceFields=curves==='both'?['close','sma60','sma200']:['close','sma'+curves];
 const chartRange=[{field:'date',label:'走势范围',value:historyRows[0].date+'..'+historyRows.at(-1).date}];
 const distRows=useMemo(()=>{const m=Number(distMA),lo=Math.floor(stats[m][1950].min),hi=Math.ceil(stats[m][1950].max),counts=Object.fromEntries(STARTS.map(y=>{const bins={};stats[m][y].values.forEach(v=>{const k=Math.floor(v);bins[k]=(bins[k]||0)+1;});return [y,bins];}));return Array.from({length:hi-lo+1},(_,i)=>Object.fromEntries([['偏离(%)',lo+i+.5],...STARTS.map(y=>['y'+y+'Share',(counts[y][lo+i]||0)/stats[m][y].n])]));},[stats,distMA]);
 const selectedEvents=events.filter(r=>r.ma===Number(eventMA)&&r.side===side&&r.horizon===Number(horizon)),metric=side==='bottom'?'p_up':'p_down',levels=LEVELS[eventMA].map(q=>side==='bottom'?-q:q);
 const q=levels.includes(Number(detailThreshold))?Number(detailThreshold):levels[2],details=selectedEvents.filter(r=>r.threshold_pct===q);
 const heatRows=states.filter(r=>r.ma===Number(heatMA)&&r.start_year===Number(year)),heatBins=heatRows.filter(r=>r.horizon===5);
 const simBias=m=>Number((100*(simPrice/latest['sma'+m]-1)).toFixed(10)),sim200=matching(200,simBias(200)),sim60=matching(60,simBias(60));
 const simTriggered=events.filter(r=>r.start_year===Number(year)&&r.horizon===20&&(r.side==='bottom'?simBias(r.ma)<=r.threshold_pct:simBias(r.ma)>=r.threshold_pct));
 const snapshotAge=Math.floor((Date.now()-Date.parse(latest.date+'T20:00:00Z'))/86400000);
 const required=(m,target)=>100*((1+target/100)/(1+latest['bias'+m]/100)-1);
 const allMiniStats=stats[miniMA],miniDomain=[Math.floor(allMiniStats[1950].min/10)*10-5,Math.ceil(allMiniStats[1950].max/10)*10+5];
 function eventTable(which,ma){
  const source=events.filter(r=>r.start_year===Number(year)&&r.ma===Number(ma)&&r.side===which),rows=LEVELS[ma].map(level=>{const threshold=which==='bottom'?-level:level,byH=source.filter(r=>r.threshold_pct===threshold),r20=byH.find(r=>r.horizon===20),r60=byH.find(r=>r.horizon===60),m=which==='bottom'?'p_up':'p_down',dates=register.filter(r=>r.ma===Number(ma)&&r.side===which&&r.threshold_pct===threshold&&r.signal_date>=year+'-01-01');return {threshold,n:r20.n,event_years:r20.event_years,small:r20.small_sample||r20.event_years<5,rate5:byH.find(r=>r.horizon===5)[m],rate20:r20[m],rate60:r60[m],mean_return:r20.mean_return,touch_up:r20.p_touch_up5,touch_down:r20.p_touch_down5,drawdown:r60.median_max_drawdown,interval:!r20.n?'无成熟样本':r20.bootstrap_degenerate?'区间退化':r20[m+'_ci95'].map(pct).join('–'),last:dates.at(-1)?.signal_date??'—'};});
  const baselineRow={threshold:'同期基准',n:baselines.find(r=>r.start_year===Number(year)&&r.horizon===20).n,rate5:base(year,5,which==='bottom'?'p_up':'p_down'),rate20:base(year,20,which==='bottom'?'p_up':'p_down'),rate60:base(year,60,which==='bottom'?'p_up':'p_down'),mean_return:null,touch_up:baselines.find(r=>r.start_year===Number(year)&&r.horizon===20).p_touch_up5,touch_down:baselines.find(r=>r.start_year===Number(year)&&r.horizon===20).p_touch_down5,drawdown:null,interval:'—',last:'—'};
  return <DataComponent id={which==='bottom'?'bottom-statistics':'top-statistics'} queryId="event_stats" queryIds={['event_stats','baselines','events']} kind="table" className="sp-panel" title={which==='bottom'?'抄底统计：首次跌破阈值后的反弹概率':'逃顶统计：首次突破阈值后的下跌概率'} displayRows={[baselineRow,...rows]} sourceRowsByQuery={{event_stats:source,baselines:baselines.filter(r=>r.start_year===Number(year)),events:register.filter(r=>r.ma===Number(ma)&&r.side===which&&r.signal_date>=year+'-01-01')}} scopeFilters={[...yearScope(year),{field:'ma',label:'均线',value:ma},{field:'side',label:'信号',value:which}]} headerControls={<SegmentedControl value={ma} options={maChoices} onChange={which==='bottom'?setBottomMA:setTopMA}/>}>
   <p className="sp-note">{year}年以来 · 首次穿越，相同阈值至少相隔61个交易日；下一交易日收盘作为参考价。期末上涨／下跌与期间触及幅度分开统计。</p>
   <DataTable rows={[baselineRow,...rows]} searchable={false} compactNumbers={false} caption={which==='bottom'?'跌破阈值后的反弹与期间风险':'突破阈值后的下跌与期间风险'} columns={[{field:'threshold',label:'触发阈值',renderCell:v=>typeof v==='number'?signed(v):v},{field:'n',label:'成熟样本数',renderCell:(v,r)=>num(v)+(typeof r.threshold==='number'?' 次':' 日')+(r.small?' · 小样本':'')},{field:'rate5',label:'5日'+(which==='bottom'?'上涨':'下跌'),renderCell:pct},{field:'rate20',label:'20日'+(which==='bottom'?'上涨':'下跌'),renderCell:pct},{field:'rate60',label:'60日'+(which==='bottom'?'上涨':'下跌'),renderCell:pct},{field:'interval',label:'20日概率95%区间'},{field:'mean_return',label:'20日平均收益',renderCell:v=>signed(v==null?null:100*v)},{field:'touch_up',label:'20日内曾涨≥5%',renderCell:pct},{field:'touch_down',label:'20日内曾跌≥5%',renderCell:pct},{field:'drawdown',label:'60日最大回撤中位数',renderCell:v=>signed(v==null?null:100*v)},{field:'last',label:'最近成熟信号'}]}/>
  </DataComponent>;
 }
 return <article className="sp500-board" style={{'--data-app-layout-intent':'user-requested','--data-app-content-width':'1280px'}}>
  <div className="sp-status" data-reviewed-rows><span><i/>指数收盘 {latest.date}{snapshotAge>4?' · 数据已过期，等待刷新':''}</span><span>真实指数 · 普通百分比偏离 · 每日 07:00 北京时间更新</span></div>
  <SortableRegion id="sp500:headline" variant="freeform" authoredRevision={2} className="sp-headline">
   <SortableItem id="index-close" label="指数收盘" kind="metric"><DataComponent id="index-close" queryId="daily" kind="metric" title="标普500 点位" className="sp-metric-card sp-blue" displayRows={[latest]} sourceRows={[previous,latest]}><div className="sp-metric" data-reviewed-rows><div className="sp-number">{num(latest.close)}</div><span className={latest.close>=previous.close?'sp-positive':'sp-negative'}>{signed(100*(latest.close/previous.close-1))} <small>较上一交易日</small></span><dl className="sp-pairs">{[60,200].map(m=><div key={m}><dt>{m}日均线 MA{m}</dt><dd>{num(latest['sma'+m])}</dd></div>)}</dl><p className="sp-note">标普500指数实际日收盘价</p></div></DataComponent></SortableItem>
   {[60,200].map(m=><SortableItem key={m} id={'bias-'+m} label={m+'日均线偏离'} kind="metric"><DataComponent id={'bias-'+m} queryId="daily" kind="metric" title={m+'日均线偏离 BIAS_'+m} className={'sp-metric-card '+(m===60?'sp-green':'sp-yellow')} displayRows={[{...latest,percentile:rank(stats[m][year].values,latest['bias'+m])}]} sourceRows={selectedDaily} scopeFilters={[{field:'date',label:'历史区间',value:year+'-01-01..'+latest.date}]}><div className="sp-metric" data-reviewed-rows><div className={'sp-number '+(latest['bias'+m]>=0?'sp-positive':'sp-negative')}>{signed(latest['bias'+m])}</div><div className="sp-subtle">{latest['bias'+m]>=0?'高于':'低于'}均线 · 所选区间第 <b>{rank(stats[m][year].values,latest['bias'+m]).toFixed(1)}%</b></div><dl className="sp-pairs">{[-(m===60?8:15),m===60?8:15].map(t=><div key={t}><dt>到偏离 {signed(t)}</dt><dd>指数需{required(m,t)>=0?'涨':'跌'} {Math.abs(required(m,t)).toFixed(2)}%</dd></div>)}</dl><Gauge stats={stats[m][year]} value={latest['bias'+m]}/></div></DataComponent></SortableItem>)}
   <SortableItem id="current-position" label="当前历史定位" kind="metric"><DataComponent id="current-position" queryId="state_stats" queryIds={['state_stats','daily','baselines']} kind="metric" title="当前读数的历史统计定位" className="sp-metric-card sp-yellow" displayRows={[...current200,...current60]} sourceRowsByQuery={{state_stats:[...current200,...current60],daily:selectedDaily,baselines:baselines.filter(r=>r.start_year===Number(year))}} scopeFilters={yearScope(year)}><div className="sp-context" data-reviewed-rows><h3>{latest.bias200<=-15?'深度负偏离观察区':latest.bias200>=15?'高位正偏离观察区':'常见偏离区间'}</h3><p>偏离度描述价格与均线的距离。历史条件概率尚未证明稳定的抄底或逃顶优势。</p><div>200日偏离所在 <b>{bin(current200[0])}</b><small>{year}年以来 · {num(current200[0]?.n??0)} 日成熟样本</small></div><div className="sp-prob-chips">{WINDOWS.map(w=><span key={w}>{w}日上涨 <b>{pct(current200.find(r=>r.horizon===w)?.p_up)}</b></span>)}</div><p>60日偏离 {bin(current60[0])}：20日上涨 <b className="sp-blue-text">{pct(current60.find(r=>r.horizon===20)?.p_up)}</b></p></div></DataComponent></SortableItem>
  </SortableRegion>
  <div className="sp-definition" data-editable-id="bias-definition">偏离 =（收盘价 ÷ 均线 − 1）× 100%。−10% 表示低于均线10%；60／200日均线均按交易日计算。</div>
  <div className="sp-period-panel"><div className="sp-period-heading"><b>统计区间：</b><SegmentedControl value={year} options={eraChoices} onChange={setYear}/></div><DataComponent id="period-baseline" queryId="baselines" kind="metric" title="无条件基准" showHeading={false} displayRows={baselines.filter(r=>r.start_year===Number(year))} sourceRows={baselines.filter(r=>r.start_year===Number(year))} scopeFilters={yearScope(year)}><div className="sp-baseline" data-reviewed-rows><span>{year}年以来 · {num(periodStats.n)} 个交易日</span><span>不按偏离筛选的上涨概率</span>{WINDOWS.map(w=><span key={w}>{w}日 <b>{pct(base(year,w))}</b></span>)}</div></DataComponent></div>
  <DataComponent id="price-history" queryId="daily" kind="custom" title="标普500走势与均线偏离度" className="sp-panel" displayRows={historyRows} sourceRows={historyRows} scopeFilters={chartRange} headerControls={<><SegmentedControl value={focusYear?'focus':range} options={[...STARTS.map(y=>({value:String(y),label:y+'+'})),{value:'5y',label:'近5年'}]} onChange={v=>{setRange(v);setFocusYear(null);}}/><SegmentedControl value={curves} options={[{value:'both',label:'双线'},{value:'200',label:'仅200日'},{value:'60',label:'仅60日'}]} onChange={setCurves}/><Switch label="滚动分位带" checked={showBand} onChange={setShowBand}/></>}>
   <p className="sp-note">上：收盘与均线，价格使用对数坐标；下：普通百分比偏离，共用真实日期范围。200日偏离阴影为低于−15%／高于+15%；虚线为过去5个自然年的5%／95%分位。悬停或用方向键查看。</p>
   <div className="sp-legend">{priceFields.map(f=><span key={f}><i style={{background:priceColors[f]}}/>{priceLabels[f]}</span>)}</div><LinePlot rows={historyRows} fields={priceFields} colors={priceColors} labels={priceLabels} log height={270} ariaLabel="标普500收盘与均线，对数价格坐标"/>
   <LinePlot rows={historyRows} fields={fields} colors={biasColors} labels={biasLabels} domain={[-50,40]} band={showBand&&curves!=='60'} zones={curves!=='60'} height={240} ariaLabel="60日和200日均线的普通百分比偏离"/>
   <div className="sp-focus-years"><span>历史年份定位：</span>{[1974,1982,1987,2000,2002,2008,2009,2020,2021,2022].map(y=><button key={y} onClick={()=>setFocusYear(y)} aria-pressed={focusYear===y}>{y}</button>)}{focusYear&&<button onClick={()=>setFocusYear(null)}>返回所选范围</button>}</div>
  </DataComponent>
  <DataComponent id="era-history" queryId="daily" kind="custom" title="四个历史区间的偏离度全貌" className="sp-panel" displayRows={daily} sourceRows={daily} headerControls={<SegmentedControl value={miniMA} options={maChoices} onChange={setMiniMA}/>}>
   <p className="sp-note">每段使用自己的真实时间轴，纵轴统一；虚线标示区间5%／95%分位和当前读数。极值标注为完整日频数据的最小值与最大值。</p><div className="sp-small-multiples">{STARTS.map((y,i)=>{const ss=stats[miniMA][y],miniRows=periods[y].map(r=>({...r,q5:ss.q5,q95:ss.q95}));return <div key={y} className="sp-mini-chart"><div className="sp-mini-title"><b style={{color:ERA_COLORS[i]}}>{y}年以来</b><span>{signed(ss.min)} ～ {signed(ss.max)}</span></div><div className="sp-reference-key">5%分位 {signed(ss.q5)} · 95%分位 {signed(ss.q95)} · 当前{miniMA}日偏离 {signed(latest['bias'+miniMA])}</div><LinePlot rows={miniRows} fields={['bias'+miniMA]} colors={{['bias'+miniMA]:ERA_COLORS[i]}} labels={biasLabels} domain={miniDomain} compact band current={latest['bias'+miniMA]} height={220} ariaLabel={y+'年以来'+miniMA+'日偏离全貌'}/></div>;})}</div>
  </DataComponent>
  <DataComponent id="deviation-distribution" queryId="daily" kind="custom" title="不同历史区间的偏离度分布对比" className="sp-panel" displayRows={distRows} sourceRows={daily} headerControls={<SegmentedControl value={distMA} options={maChoices} onChange={setDistMA}/>}>
   <p className="sp-note">每1个百分点分箱，纵轴为该区间交易日占比；所选区间加粗填充，棕色虚线为当前读数。</p><div className="sp-legend">{STARTS.map((y,i)=><span key={y}><i style={{background:ERA_COLORS[i]}}/>{y}年以来</span>)}</div><LinePlot rows={distRows} fields={STARTS.map(y=>'y'+y+'Share')} colors={Object.fromEntries(STARTS.map((y,i)=>['y'+y+'Share',ERA_COLORS[i]]))} labels={Object.fromEntries(STARTS.map(y=>['y'+y+'Share',y+'年以来']))} xField="偏离(%)" fraction verticalAt={latest['bias'+distMA]} highlight={'y'+year+'Share'} height={320} ariaLabel="四段历史的偏离度分布与当前位置"/>
   <div className="sp-era-grid">{STARTS.map(y=><EraStats key={y} stats={stats[distMA][y]} value={latest['bias'+distMA]} year={y} active={String(y)===year}/>)}</div>
  </DataComponent>
  <DataComponent id="threshold-probability" queryId="event_stats" kind="custom" title="阈值触发后的前向概率梯队（跨区间对比）" className="sp-panel" displayRows={selectedEvents} sourceRows={selectedEvents} scopeFilters={[{field:'ma',label:'均线',value:eventMA},{field:'side',label:'信号',value:side},{field:'horizon',label:'窗口',value:horizon}]} headerControls={<><SegmentedControl value={side} options={[{value:'bottom',label:'抄底 · 上涨概率'},{value:'top',label:'逃顶 · 下跌概率'}]} onChange={setSide}/><SegmentedControl value={eventMA} options={[{value:'60',label:'60日'},{value:'200',label:'200日'}]} onChange={setEventMA}/><SegmentedControl value={horizon} options={WINDOWS.map(w=>({value:String(w),label:w+'交易日'}))} onChange={setHorizon}/></>}>
   <p className="sp-note">{side==='bottom'?'低于均线多少后，期末上涨概率的变化':'高于均线多少后，期末下跌概率的变化'}。首次穿越事件，相同阈值至少相隔61个交易日，四个区间相互嵌套。</p><div className="sp-bars-scroll"><ThresholdBars rows={selectedEvents} levels={levels} metric={metric} horizon={horizon}/></div><p className="sp-note">柱内为事件数 n；淡色柱：n &lt; 30 或发生年份 &lt; 5。无成熟样本显示“—”。</p>
   <details className="sp-details"><summary>查看阈值的置信区间与同期基准</summary><Dropdown label="偏离阈值" showLabel value={String(q)} choices={levels.map(String)} formatChoice={v=>signed(Number(v))} onChange={setDetailThreshold}/><DataTable rows={details.map(r=>({...r,period:r.start_year+'年以来',target:r[metric],interval:!r.n?'无成熟样本':r.bootstrap_degenerate?'区间退化，勿解读':r[metric+'_ci95'].map(pct).join('–'),base:base(r.start_year,Number(horizon),metric),diff:r.n?100*(r[metric]-base(r.start_year,Number(horizon),metric)):null}))} caption="四段历史的阈值事件统计" searchable={false} columns={[{field:'period',label:'历史区间'},{field:'n',label:'事件数'},{field:'event_years',label:'发生年份数'},{field:'target',label:'目标概率',renderCell:pct},{field:'interval',label:'年簇95%区间'},{field:'base',label:'同期基准',renderCell:pct},{field:'diff',label:'概率差',renderCell:pp}]}/></details>
  </DataComponent>
  <DataComponent id="state-heatmap" queryId="state_stats" kind="table" title="偏离区间 × 持有窗口 概率热力表" className="sp-panel" displayRows={heatRows} sourceRows={heatRows} scopeFilters={[...yearScope(year),{field:'ma',label:'均线',value:heatMA}]} headerControls={<><SegmentedControl value={heatMA} options={maChoices} onChange={setHeatMA}/><SegmentedControl value={heatMetric} options={[{value:'p_up',label:'上涨概率'},{value:'p_down',label:'下跌概率'}]} onChange={setHeatMetric}/></>}>
   <p className="sp-note">{year}年以来全部成熟观察日，连续日期会重叠。概率为期末收盘高于／低于参考价，均收益为窗口内期末平均收益。</p><div className="sp-table-wrap" data-reviewed-rows><table className="sp-heatmap"><thead><tr><th>偏离区间</th>{WINDOWS.map(w=><th key={w}>{w}交易日后</th>)}</tr></thead><tbody>{heatBins.map(r=><tr key={bin(r)}><th scope="row">{bin(r)}{inBin(latest['bias'+heatMA],r)&&<em>当前</em>}</th>{WINDOWS.map(w=><HeatCell key={w} metric={heatMetric} row={heatRows.find(x=>x.bin_low===r.bin_low&&x.bin_high===r.bin_high&&x.horizon===w)}/>)}</tr>)}</tbody></table></div>
  </DataComponent>
  <DataComponent id="scenario-simulation" queryId="state_stats" queryIds={['state_stats','daily','event_stats']} kind="custom" title="情景模拟：如果指数到某个点位" className="sp-panel" displayRows={[...sim200,...sim60].map(r=>({...r,scenario_price:simPrice,scenario_bias60:simBias(60),scenario_bias200:simBias(200)}))} sourceRowsByQuery={{state_stats:[...sim200,...sim60],daily:selectedDaily,event_stats:simTriggered}} scopeFilters={[...yearScope(year),{field:'scenario_price',label:'假设点位',value:simPrice}]}>
   <p className="sp-note">基于 {latest.date} 的两条均线保持不变，三项滑块联动；概率直接查询对应历史分箱，不插值、不外推。未来均线会随行情变化。</p><div className="sp-sim-sliders"><Slider label="模拟标普500点位" min={Math.floor(latest.sma200*.5)} max={Math.ceil(latest.sma60*1.5)} step={1} value={simPrice} onChange={setSimPrice} formatValue={v=>num(v)+' 点'}/>{[60,200].map(m=><Slider key={m} label={'模拟'+m+'日偏离度'} min={100*(Math.floor(latest.sma200*.5)/latest['sma'+m]-1)} max={100*(Math.ceil(latest.sma60*1.5)/latest['sma'+m]-1)} step={.1} value={simBias(m)} onChange={v=>setSimPrice(latest['sma'+m]*(1+v/100))} formatValue={signed}/>)}</div><div className="sp-focus-years"><span>快速情景：</span><button onClick={()=>setSimPrice(latest.close)}>收盘基准</button>{[['温和回调',-5],['中级调整',-10],['深度负偏离',-15],['极端负偏离',-25],['高位偏离',15]].map(([name,b])=><button key={name} onClick={()=>setSimPrice(latest.sma200*(1+b/100))}>{name} · {num(Math.round(latest.sma200*(1+b/100)))}</button>)}</div>
   <div className="sp-sim-summary" data-reviewed-rows><div className="sp-mini-title"><b>模拟读数 · {num(simPrice)} 点</b><span>200日偏离 {signed(simBias(200))} · 60日偏离 {signed(simBias(60))}</span></div><p className="sp-note">{year}年以来：200日偏离位于 {bin(sim200[0])}，{num(sim200[0]?.n??0)} 日成熟样本；60日位于 {bin(sim60[0])}，{num(sim60[0]?.n??0)} 日。以下概率使用200日分箱。</p><div className="sp-sim-grid"><div><span>200日历史分位</span><strong>{rank(stats[200][year].values,simBias(200)).toFixed(1)}%</strong></div><div><span>60日历史分位</span><strong>{rank(stats[60][year].values,simBias(60)).toFixed(1)}%</strong></div>{WINDOWS.map(w=>{const r=sim200.find(r=>r.horizon===w);return <div key={w}><span>{w}日上涨概率</span><strong>{pct(r?.p_up)}</strong><small>均收益 {signed(r?.mean_return==null?null:100*r.mean_return)}</small></div>;})}<div><span>20日概率95%区间</span><strong className="sp-ci-value">{ci(sim200.find(r=>r.horizon===20))}</strong></div></div><div className="sp-sim-events"><b>所处位置对应的事件阈值</b><p className="sp-note">仅比较阈值位置；滑块不能判断未来是否首次穿越或处于冷却期。</p>{simTriggered.length?simTriggered.map(r=><span key={r.ma+':'+r.threshold_pct}>{r.ma}日 {r.side==='bottom'?'≤':'≥'} {signed(r.threshold_pct)} · n={r.n} · 20日{r.side==='bottom'?'上涨':'下跌'} {pct(r[r.side==='bottom'?'p_up':'p_down'])}{r.small_sample||r.event_years<5?' · 小样本':''}</span>):<p>该位置没有达到已统计的事件阈值。</p>}</div></div>
  </DataComponent>
  {eventTable('bottom',bottomMA)}{eventTable('top',topMA)}
  <DataComponent id="event-register" queryId="events" kind="table" title="历史信号明细" className="sp-panel" displayRows={register.filter(r=>r.ma===Number(eventMA)&&r.side===side&&r.threshold_pct===q&&r.signal_date>=year+'-01-01')} sourceRows={register.filter(r=>r.ma===Number(eventMA)&&r.side===side&&r.threshold_pct===q&&r.signal_date>=year+'-01-01')} scopeFilters={[...yearScope(year),{field:'ma',label:'均线',value:eventMA},{field:'side',label:'方向',value:side},{field:'threshold_pct',label:'阈值',value:q}]}>
   <details className="sp-details"><summary>{year}年以来 · {eventMA}日 · {side==='bottom'?'跌破':'突破'} {signed(q)} · 展开成熟信号</summary><DataTable rows={register.filter(r=>r.ma===Number(eventMA)&&r.side===side&&r.threshold_pct===q&&r.signal_date>=year+'-01-01')} rowKey="signal_date" caption="当前阈值的成熟历史信号" columns={[{field:'signal_date',label:'信号日'},{field:'reference_date',label:'参考日'},{field:'deviation_pct',label:'当日偏离',renderCell:signed},{field:'reference_close',label:'参考收盘',renderCell:num},...WINDOWS.map(w=>({field:'return_'+w,label:w+'日收益',renderCell:v=>signed(100*v)}))]}/></details>
  </DataComponent>
  <div className="sp-panel sp-methods"><h2 data-editable-id="methods-heading">研究口径与局限</h2><div className="sp-method-grid"><div><h3>普通百分比偏离</h3><p>100 ×（收盘／简单移动均线 − 1）。均线包含当日；1950年前199个收盘仅用于预热，图表从1950年开始。1957年前为标普前身历史序列。</p></div><div><h3>事件与重叠观察日</h3><p>首次穿越阈值，相同阈值至少相隔61个交易日。四段区间相互嵌套；分箱使用每日重叠观察，不能把 n 当作独立交易数。</p></div><div><h3>参考价与不确定性</h3><p>参考价为下一交易日收盘，再计算5／20／60交易日收益。共同成熟的最后信号日 {snapshot.research.last_eligible_signal}。95%区间按自然年重采样5000次；全成／全败区间会退化。</p></div><div><h3>每日更新与使用边界</h3><p>行情与历史概率计划每天北京时间07:00重算，休市保留最近真实收盘。不含分红、成本、税费与现金收益。深度负偏离可以作为超跌观察信号，尚未证明稳定优势。</p></div></div><div className="sp-method-date" data-reviewed-rows>价格数据：{daily[0].date} → {latest.date} · {num(daily.length)} 个交易日 · 数据核验 {snapshot.generatedAt.slice(0,10)}</div></div>
 </article>;
}
